name: Deploy

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Docker tag
        id: docker-tag
        run: echo "::set-output name=tag::$(echo $GITHUB_SHA | head -c7)"

      - name: Set rails MASTER_KEY
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: echo "$RAILS_MASTER_KEY" > config/credentials/production.key

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: switchdreams
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push sonicscript
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            GH_PACKAGE_TOKEN=${{ secrets.GH_PACKAGE_TOKEN }}
          push: true
          tags: switchdreams/projects:sonicscript-${{ steps.docker-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'https://sonicscript.com.br/'

    steps:
      - name: Check out Switch Deployment repository
        uses: actions/checkout@master
        with:
          repository: SwitchDreams/switch-deployment
          token: ${{ secrets.SWITCH_DEPLOYMENT_PAT }}
          persist-credentials: true

      - name: Set up yq
        uses: frenck/action-setup-yq@v1

      - name: Switch image tag in Helm Values file
        env:
          DOCKER_TAG: sonicscript-${{ needs.build.outputs.docker-tag }}
        run: |
          yq -i e '.deployment.api.image.tag = "${{env.DOCKER_TAG}}"' sonicscript-production/values.yaml
          yq -i e '.deployment.worker.image.tag = "${{env.DOCKER_TAG}}"' sonicscript-production/values.yaml

      - name: Commit files to Switch Deployment repository
        run: |
          git config --local user.email "joaopedroassisdossantos@gmail.com"
          git config --local user.name "João Pedro Assis"
          git add .
          git commit -m "Update Sonicscript tag to ${{ needs.build.outputs.docker-tag }}"
          git push