name: Frontend CI
on:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@switchdreams'

      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
      - name: Run Tests
        env:
          TZ: "America/Sao_Paulo"
        run: yarn vitest